---

- include_tasks: dependencies.yml
  tags: [rbenv]

- include_tasks: rbenv.yml
  tags: [rbenv]

- include_tasks: ruby-build.yml
  tags: [rbenv]

- include_tasks: ruby-version.yml
  with_items: "{{ rbenv_ruby_versions }}"

- name: "Set global ruby version to {{ rbenv_global_ruby_version }}"
  command: $SHELL -lc "rbenv global {{ rbenv_global_ruby_version }}"

- name: Rehash rbenv
  command: $SHELL -lc "rbenv rehash"
